
// SCHEDULE Actions
const ADD_SCHEDULE = 'ADD_SCHEDULE';
const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
const REMOVE_SCHEDULE = 'REMOVE_SCHEDULE';
const REMOVE_DEVICE_SCHEDULES = 'REMOVE_DEVICE_SCHEDULES';
const ACTIVATE_SCHEDULE = 'ACTIVATE_SCHEDULE';

const RESET_SCHEDULE_TO_ADD = "RESET_SCHEDULE_TO_ADD";
const UPDATE_SCHEDULE_TO_ADD = "UPDATE_SCHEDULE";
const INSERT_SCHEDULE_TO_ADD = "INSERT_SCHEDULE";

// DEVICE Actions
const ADD_DEVICE = 'ADD_DEVICE';
const REMOVE_DEVICE = 'REMOVE_DEVICE';
const RENAME_DEVICE = 'RENAME_DEVICE';


// Current Device Actions
const UPDATE_CURRENT_DEVICE = 'UPDATE_CURRENT_DEVICE';
const RESET_CURRENT_DEVICE = 'RESET_CURRENT_DEVICE';


// Navigation state
const REPLACE_CURRENT_SCREEN = "REPLACE_CURRENT_SCREEN"; 
const UPDATE_CURRENT_TAB = "UPDATE_NAVIGATION_TAB";

export {
    // schedules
    ADD_SCHEDULE,
    UPDATE_SCHEDULE,
    REMOVE_SCHEDULE,
    REMOVE_DEVICE_SCHEDULES,
    ACTIVATE_SCHEDULE,
    // device
    ADD_DEVICE,
    REMOVE_DEVICE,
    RENAME_DEVICE,
    // current devices
    UPDATE_CURRENT_DEVICE,
    RESET_CURRENT_DEVICE,
    //Navigation
    REPLACE_CURRENT_SCREEN,
    UPDATE_CURRENT_TAB

};