
// SCHEDULE Actions
const ADD_SCHEDULE = 'ADD_SCHEDULE';
const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
const REMOVE_SCHEDULE = 'REMOVE_SCHEDULE';
const REMOVE_DEVICE_SCHEDULES = 'REMOVE_DEVICE_SCHEDULES';


// DEVICE Actions
const ADD_DEVICE = 'ADD_DEVICE';
const REMOVE_DEVICE = 'REMOVE_DEVICE';
const RENAME_DEVICE = 'RENAME_DEVICE';


export {
    ADD_SCHEDULE,
    UPDATE_SCHEDULE,
    REMOVE_SCHEDULE,
    REMOVE_DEVICE_SCHEDULES,
    ADD_DEVICE,
    REMOVE_DEVICE,
    RENAME_DEVICE
};